<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Jellyfin.Plugin.VirtualTV</AssemblyName>
    <RootNamespace>Jellyfin.Plugin.VirtualTV</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.0.10.0</Version>
    <AssemblyVersion>1.0.10.0</AssemblyVersion>
    <FileVersion>1.0.10.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="12.1.0">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Jellyfin.Model" Version="12.1.0">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Remove="Configuration/configPage.html" />
    <EmbeddedResource Include="Configuration/configPage.html" />
  </ItemGroup>

</Project>
